name: Secrets workflow
on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Package installation
      run: pip install python-dotenv
    - run: | 
        import os
        print(len(os.getenv('MY_VAR')))
      shell: python
      env: 
        MY_VAR: ${{ secrets.MY_SECRET }}