name: Secrets workflow
on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Package installation
      run: pip install python-dotenv
    - run: | 
        from dotenv import load_dotenv
        load_dotenv()
        print(os.environ.get('MY_VAR'))
      shell: python
      env: 
        MY_VAR: ${{ secrets.MY_SECRET }}